# Generated by Django 4.1.3 on 2022-11-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('foto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('url_git', models.CharField(blank=True, max_length=250, null=True)),
                ('url_proyecto', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyecto.categoria')),
            ],
        ),
    ]
