# Generated by Django 4.1.3 on 2022-11-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(max_length=1250),
        ),
    ]
