# Generated by Django 4.1.3 on 2022-11-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
